# .github/workflows/fortify.yml

name: Fortify AST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Add your build steps here based on your language breakdown
      # This is the most crucial part to customize for your project
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add any other Python dependency commands here

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          npm install
          # Add any other TypeScript/JavaScript dependency commands here

      - name: Build project
        run: |
          # Replace this with your actual build command
          # For example, 'npm run build' or 'python setup.py build'
          echo "No specific build command provided, skipping build step."

      # Run the Fortify scan
      - name: Run Fortify Scan
        uses: fortify/github-action@v2
        with:
          sast-scan: true
          # Note: debricked-sca-scan: true is only for FoD and should be enabled if you have a license
        env:
          # Required Fortify on Demand configuration
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          # You can use client credentials instead of user credentials
          # FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          # FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}

          # Optional Configuration - Uncomment and customize as needed
          DO_EXPORT: true # Exports results to GitHub's code scanning dashboard
          DO_WAIT: true # Waits for scan to complete before finishing the job
          DO_POLICY_CHECK: true # Fails the build if the security policy fails
          # PACKAGE_EXTRA_OPTS: "-bt pip -bt npm" # Use this to help Fortify's packager
